<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' => 'Ana López',
                'email' => 'ana.lopez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle Falsa 123, Ciudad',
                'phone' => '1234567890',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luis García',
                'email' => 'luis.garcia@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida Siempre Viva 456, Ciudad',
                'phone' => '0987654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'María Fernández',
                'email' => 'maria.fernandez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle 7, Barrio Alto',
                'phone' => '1122334455',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos Martínez',
                'email' => 'carlos.martinez@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle Principal 789, Ciudad',
                'phone' => '5566778899',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laura Gómez',
                'email' => 'laura.gomez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida Central 101, Ciudad',
                'phone' => '6677889900',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pedro Rodríguez',
                'email' => 'pedro.rodriguez@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle del Sol 202, Ciudad',
                'phone' => '7788990011',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Claudia Pérez',
                'email' => 'claudia.perez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle del Mar 303, Ciudad',
                'phone' => '8899001122',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fernando Díaz',
                'email' => 'fernando.diaz@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida Libertad 404, Ciudad',
                'phone' => '9900112233',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sofía Morales',
                'email' => 'sofia.morales@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Luna 505, Ciudad',
                'phone' => '1010101010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jorge López',
                'email' => 'jorge.lopez@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle del Río 606, Ciudad',
                'phone' => '2020202020',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marta Sánchez',
                'email' => 'marta.sanchez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida de la Paz 707, Ciudad',
                'phone' => '3030303030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ricardo Castro',
                'email' => 'ricardo.castro@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de los Pinos 808, Ciudad',
                'phone' => '4040404040',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Patricia Ruiz',
                'email' => 'patricia.ruiz@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Estrella 909, Ciudad',
                'phone' => '5050505050',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andrés Ortega',
                'email' => 'andres.ortega@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida del Norte 010, Ciudad',
                'phone' => '6060606060',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Verónica Vargas',
                'email' => 'veronica.vargas@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Primavera 121, Ciudad',
                'phone' => '7070707070',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Gómez',
                'email' => 'david.gomez@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle del Bosque 232, Ciudad',
                'phone' => '8080808080',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carolina Silva',
                'email' => 'carolina.silva@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida del Sur 343, Ciudad',
                'phone' => '9090909090',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sergio Ramírez',
                'email' => 'sergio.ramirez@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Aventura 454, Ciudad',
                'phone' => '0101010101',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabel Romero',
                'email' => 'isabel.romero@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle del Jardín 565, Ciudad',
                'phone' => '1212121212',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alejandro Soto',
                'email' => 'alejandro.soto@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida del Sol 676, Ciudad',
                'phone' => '2323232323',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabriela Martínez',
                'email' => 'gabriela.martinez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Alegría 787, Ciudad',
                'phone' => '3434343434',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mauricio Castillo',
                'email' => 'mauricio.castillo@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Felicidad 898, Ciudad',
                'phone' => '4545454545',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Natalia Torres',
                'email' => 'natalia.torres@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida de la Esperanza 909, Ciudad',
                'phone' => '5656565656',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Javier López',
                'email' => 'javier.lopez@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle de la Risa 010, Ciudad',
                'phone' => '6767676767',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daniela López',
                'email' => 'daniela.lopez@gmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Calle del Encanto 121, Ciudad',
                'phone' => '7878787878',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Felipe Morales',
                'email' => 'felipe.morales@hotmail.com',
                'password' => Hash::make('password123'),
                'address' => 'Avenida del Amor 232, Ciudad',
                'phone' => '8989898989',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
